# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
library(pkgload)
pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
PAMPortal::run_app() # add parameters here (if any)
